vigetlabs/wordpress-site-starter

- wp-content/themes/wp-starter/blocks/text-image/block.json
- wp-content/themes/wp-starter/src/styles/blocks/logo-grid.css
- wp-content/themes/wp-starter/src/styles/blocks/text-image.css
- wp-content/themes/wp-starter/src/styles/main.css
- wp-content/themes/wp-starter/src/theme-json/settings/spacing.js
- wp-content/themes/wp-starter/tailwind.config.js
Styling the component to match the design and BP. 
* #7
1. Add the text-image component to the page.
> [#7] Styling text-image

- README.dist.md
- README.md
- wp-content/themes/wp-starter/README.md
Updating the readme files for users:
1. Developer working on the WP site starter files.
2. Developer starting up a new client project using the WP site starter files.
3. Developer setting up the client project on local dev.
The main `README` is for instance number 1. The `README.dist` is for instance number 2 and 3. 
* #53
1. Read through both readme and make sure what I added cover everything. 
NA
> [#53] Adding readme updates

- wp-content/themes/wp-starter/blocks/breadcrumbs/block.json
- wp-content/themes/wp-starter/blocks/breadcrumbs/patterns/breadcrumbs-inner-blocks.php
- wp-content/themes/wp-starter/blocks/page-header/patterns/page-header-inner-blocks.php
- wp-content/themes/wp-starter/src/styles/custom-blocks/breadcrumbs.css
- wp-content/themes/wp-starter/src/styles/main.css
Styles the breadcrumbs with TW
* #69
1. Make sure the breadcrumbs look like the screenshots.
> [#69] Styling the breadcrumbs

- bin/composer-scripts/.phpcs.xml
- bin/composer-scripts/ProjectEvents/PostCreateProjectScript.php
So I noticed that when you create a new site it does not do a search/replace on the twig files. Once I found the line of code I saved it and noticed that the composer files don't have a default PHP cs (so mine defaulted to WP and changed everything). I added a `.phpcs` file based on PSR12 which is pretty much what Craft follows so we have a base php format for the files in the bin.
* #90
1. No way to test this until we merge with `main` and run `composer create-project --prefer-dist --stability=dev viget/wordpress-site-starter:dev-main` 
NA
> [#90] Fixing placeholder bug, adding phpcs file for bin

- README.dist.md
- bin/composer-scripts/ProjectEvents/PostInstallScript.php
At the end of the composer install it is not very clear what the username is for the admin. So that is now added. 
* #91
1. NA
NA
> [#91] Adding admin user name to post install

- bin/composer-scripts/ProjectEvents/PostInstallScript.php
The composer install does not delete the themes or the plugins. These two may to happen after the DB. So trying to run both of these after the DB is set up. 
@bd-viget not sure about this fix, but it may be the problem. You may have a better idea on what is going on and why the files are not getting removed. 
* #93
1. Can not test till merged with `main` and we run the install.
> [#93] Moving the delating to after DB install

- bin/composer-scripts/ProjectEvents/PostInstallScript.php
This updates the composer post install `deleteCoreThemes` and `deleteCorePlugins` to return a warning if WP is not installed. 
I also noticed that I mistakenly added `isWordPressInstalled` to  `activatePlugins`, which is now removed. 
* NA
1. NA
> [n/a] Updating delete theme/plugins to warning

- wp-content/mu-plugins/viget-wp/src/assets/js/skip-cropping.js
- wp-content/mu-plugins/viget-wp/src/classes/Admin/Assets.php
Allows the user to skip the cropping step when uploading a site icon in the case of the icon being an SVG.
* #114 
1. Upload SVG to Site Icon under Settings > General
2. Click Skip Cropping
3. Save Changes
> [#114] Allow Skip Cropping

- wp-content/themes/wp-starter/src/styles/core-blocks/list.css
This PR fixes an issue where elements were displayed `inline-block` in the editor.
* #108 
1. Create a CTA block.
2. View on a wide screen inside the editor
3. Make sure the heading and paragraph elements are not inline with each other.
**Fixes this issue**
> [N/A] Fix editor bug w/inline-block

- .ddev/config.yaml
- bin/composer-scripts/ProjectEventHandler.php
- bin/composer-scripts/ProjectEvents/PostInstallScript.php
- wp-content/mu-plugins/viget-wp/composer.json
- wp-content/mu-plugins/viget-wp/src/classes/Features/Gravatar.php
This PR fixes an issue where WordPress doesn't get installed when cloning the repo for the first time, causing a 403 Forbidden when it runs `ddev launch`.
* #111 
1. Clone this repo
2. Run `ddev start`
> [#111] Installation Fixes

- wp-content/themes/wp-starter/templates/404.html
Adds the 404 template page to the starter.
* #122 
1. Go to a nonpage like `/testing` and make sure the 404 content shows up. 
NA
> [#122] 404 page

- bin/composer-scripts/ProjectEvents/PostInstallScript.php
- wp-content/themes/wp-starter/composer.json
- wp-content/themes/wp-starter/composer.lock
Adding the [Accessibility Checker](https://equalizedigital.com/) plugin. We found this plugin on GoodBids and the plugins checks the page like the WAVE tool but in the WP page editor. Helps our team when running QA/a11y and helps our clients keep the site accessible. 
* #126
1. My need to re-run composer
2. Once this is merged we will test new build and make sure the plugin is added.
> [#126] Adding the plugin accessibility-checker to our default build

- .vscode/settings.json
- wp-content/themes/wp-starter/README.md
- wp-content/themes/wp-starter/package-lock.json
- wp-content/themes/wp-starter/package.json
- wp-content/themes/wp-starter/plop-templates/block.json.hbs
- wp-content/themes/wp-starter/plop-templates/parts/css-link.css.hbs
- wp-content/themes/wp-starter/plop-templates/parts/styles.json.hbs
- wp-content/themes/wp-starter/plop-templates/parts/variations.json.hbs
- wp-content/themes/wp-starter/plop-templates/patterns/{{dashCase name}}-inner-blocks.php.hbs
- wp-content/themes/wp-starter/plop-templates/render.twig.hbs
- wp-content/themes/wp-starter/plop-templates/style.css.hbs
- wp-content/themes/wp-starter/plopfile.js
- wp-content/themes/wp-starter/src/styles/custom-blocks.css
- wp-content/themes/wp-starter/src/styles/main.css
This adds [plop](https://plopjs.com/) which allows us to auto build block files from the templates. We ask several questions and then build all the files. 
* #129
1. Restart DDEV by running `ddev restart`
2. Then path into the theme `wp-content/themes/wp-starter`
3. Run `ddev npm run plop block` or `ddev npm run plop` - running without  `block` plop will default to the first generator which is `block`.
> [#129] Auto Create Blocks

- wp-content/plugins/acf-blocks-toolkit/includes/helpers.php
- wp-content/plugins/acf-blocks-toolkit/src/classes/BlockRegistration.php
- wp-content/themes/wp-starter/blocks/accordion/render.twig
- wp-content/themes/wp-starter/blocks/alert-banner/render.twig
- wp-content/themes/wp-starter/blocks/breadcrumbs/render.twig
- wp-content/themes/wp-starter/blocks/cta/render.twig
- wp-content/themes/wp-starter/blocks/image-caption/render.twig
- wp-content/themes/wp-starter/blocks/logo-grid/render.twig
- wp-content/themes/wp-starter/blocks/navigation-container/render.twig
- wp-content/themes/wp-starter/blocks/page-header/render.twig
- wp-content/themes/wp-starter/blocks/text-icon-cards/render.twig
- wp-content/themes/wp-starter/blocks/text-icon-cards/text-icon-card/render.twig
- wp-content/themes/wp-starter/blocks/text-image/render.twig
- wp-content/themes/wp-starter/blocks/video-embed/render.twig
This PR contains changes made to the ACF Blocks Toolkit plugin during the development of ACF Form Blocks plugin.
* Adds support for Unique Persistent Block IDs
* Slight refactor of `block_attrs()` to be cleaner and more consistent
* Allows block templates (inner blocks) to be specified in the `block.json` file under the `"acf"` object, accessible from `$block['template']`.
* Provides additional helpful variables to the `render.php` (and `render.twig`), as well as renames `attributes` to `block` to be more consistent with the PHP template.
* `int $post_id`
* `WP_Block $wp_block`
* `array|bool $context` (usually array)
* `bool $is_ajax_render`
* N/A
> [N/A] ACF Blocks Toolkit Changes from Block Forms branch

- wp-content/plugins/acf-blocks-toolkit/src/classes/BlockRegistration.php
This PR is a bug fix that resets the Block IDs transient at the start of a new request to ensure a new set of IDs is being used when creating Block IDs and checking for duplicates.
* N/A/
1. Using a block that supports `block_id`, add one or more to a page.
2. Make changes and save within 1 min of the previous save
3. Ensure the Block ID(s) have not changed. (`$block['block_id']`)
> [N/A] Prevent Block IDs from Changing

- wp-content/plugins/acf-blocks-toolkit/includes/helpers.php
- wp-content/themes/wp-starter/inc/class-vite.php
Fixes the css missing in preview mode.
Removes the duplicate Vite call. 
Adds our custom css/js at the vary bottom of the `head` tag which fixes the `importmap` error
* #141
1. Make sure there is no `importmap` error in the console.
2. If you view a page in Preview the styles look the same.
NA
> [#141] Fixing css/js bugs with preview and console log

- .github/workflows/deploy.yaml
- bin/composer-scripts/ProjectEvents/PostCreateProjectScript.php
- bin/composer-scripts/ProjectEvents/PostInstallScript.php
- wp-content/themes/wp-starter/composer.json
- wp-content/themes/wp-starter/composer.lock
- wp-content/themes/wp-starter/readme.txt
This PR eradicates SVG Support and replaces it with Safe SVG. This was supposed to be in the last PR, however, something weird happened with the `composer` file (maybe a bad merge), and it still remained.
I just realized some of this work is duplicated in [this PR](https://github.com/vigetlabs/wordpress-site-starter/pull/153), but this solution is a bit more robust, and cleans up some WP Site Starter specific GitHub files.
1. On a fresh install, the Safe SVG plugin should be included, not SVG Support.
> [N/A] SVG Support Removal

- bin/composer-scripts/ProjectEvents/PostCreateProjectScript.php
- bin/composer-scripts/ProjectEvents/PostInstallScript.php
This prevents the `composer` scripts from running unless in Dev Mode.
* N/A
1. Run a deployment
2. Hopefully everything deploys.
> [N/A] Disable Composer Script if not in Dev Mode

- wp-content/themes/wp-starter/blocks/navigation-container/render.php
- wp-content/themes/wp-starter/blocks/navigation-container/render.twig
This PR allows the Core Search block to be added to the Navigation Container block.
* N/A
1. Try to add the Search block as a child of the Navigation Container block.
> [N/A] Allow Core Search block in Navigation Container

- wp-content/themes/wp-starter/README.md
- wp-content/themes/wp-starter/blocks/accordion/style.css
- wp-content/themes/wp-starter/blocks/alert-banner/style.css
- wp-content/themes/wp-starter/blocks/breadcrumbs/style.css
- wp-content/themes/wp-starter/blocks/navigation-container/render.php
- wp-content/themes/wp-starter/blocks/navigation-container/render.twig
- wp-content/themes/wp-starter/blocks/page-header/block.json
- wp-content/themes/wp-starter/parts/footer-stacked-navigation.html
- wp-content/themes/wp-starter/parts/footer.html
- wp-content/themes/wp-starter/src/plugins-tailwind/buttons.js
- wp-content/themes/wp-starter/src/styles/core-blocks/buttons.css
- wp-content/themes/wp-starter/src/styles/core-blocks/navigation.css
- wp-content/themes/wp-starter/src/styles/core-blocks/quote.css
- wp-content/themes/wp-starter/src/theme-json/styles/blocks.js
- wp-content/themes/wp-starter/tailwind.config.js
- wp-content/themes/wp-starter/theme.json
Removes instances of `accentColor` and references to it, along with all gray color references.
* N/A
> [N/A] Remove accentColor Dev Feature

- wp-content/mu-plugins/viget-wp.php
- wp-content/mu-plugins/viget-wp/.editorconfig
- wp-content/mu-plugins/viget-wp/README.md
- wp-content/mu-plugins/viget-wp/src/assets/css/admin.css
- wp-content/mu-plugins/viget-wp/src/assets/js/custom-scripts.js
- wp-content/mu-plugins/viget-wp/src/classes/Admin/CustomScripts.php
- wp-content/mu-plugins/viget-wp/src/classes/Core.php
- wp-content/mu-plugins/viget-wp/views/admin/custom-scripts.php
- wp-content/mu-plugins/viget-wp/viget-wp.php
This PR adds a Custom Scripts page to the Tools menu, allowing admins to insert custom scripts into the `<head>` and `<body>` tags. This will render globally and do not have any way of rendering conditionally.
* N/A
1. Visit WP Admin
2. Go to Tools > Custom Scripts
3. Add custom scripts
4. Save changes
5. Review to ensure they are rendered properly on the front-end.
> [N/A] Add Custom Scripts Tools Page

- .vscode/settings.json
- README.dist.md
- README.md
- wp-content/themes/wp-starter/README.md
This updates the theme readme and the main repo readme.
- Adds links to the theme readme.
- Updates Buttons as we no longer are using the TW buttons JS.
- Adds some reference links. 
- Adds more info on creating Buttons Styles pulled from our [developer guide](https://www.notion.so/viget/WP-Site-Starter-Developer-Guide-12a6c4ac83fe8041ae82d3d4b4f38cf3?pvs=4).
- Adds a troubleshooting section which is taken from our [developer guide](https://www.notion.so/viget/WP-Site-Starter-Developer-Guide-12a6c4ac83fe8041ae82d3d4b4f38cf3?pvs=4).
* #123
> [#123] Readme Updates

- .gitignore
- .vscode/wp-starter.code-workspace
- bin/composer-scripts/ProjectEvents/PostCreateProjectScript.php
- bin/composer-scripts/ProjectEvents/PostInstallScript.php
- bin/composer-scripts/ProjectEvents/PreScripts.php
- wp-content/themes/wp-starter/.phpcs.xml
- wp-content/themes/wp-starter/blocks/alert-banner/block.php
- wp-content/themes/wp-starter/blocks/alert-banner/render.php
- wp-content/themes/wp-starter/blocks/alert-banner/render.twig
- wp-content/themes/wp-starter/blocks/breadcrumbs/block.php
- wp-content/themes/wp-starter/blocks/breadcrumbs/render.php
- wp-content/themes/wp-starter/blocks/breadcrumbs/render.twig
- wp-content/themes/wp-starter/blocks/image-caption/render.php
- wp-content/themes/wp-starter/blocks/navigation-container/render.php
- wp-content/themes/wp-starter/blocks/navigation-container/render.twig
- wp-content/themes/wp-starter/blocks/navigation-container/template.json
- wp-content/themes/wp-starter/blocks/video-player/block.php
- wp-content/themes/wp-starter/blocks/video-player/render.php
- wp-content/themes/wp-starter/blocks/video-player/render.twig
- wp-content/themes/wp-starter/composer.json
- wp-content/themes/wp-starter/composer.lock
- wp-content/themes/wp-starter/functions.php
- wp-content/themes/wp-starter/inc/blocks.php
- wp-content/themes/wp-starter/inc/class-vite.php
- wp-content/themes/wp-starter/inc/icons.php
This PR primarily adds Viget Form Blocks and Viget Parts Kit plugins to the WP Site Starter, but also contains a few other tweaks.
* N/A
1. Still working out some kinks.
> Misc Changes
